---
apiVersion: v1
kind: ConfigMap
metadata:
  name: travel-avail
  namespace: {{ .Values.namespace }}
data:
  LISTEN_ADDR: 0.0.0.0:8080
  UPSTREAM_URIS: "http://travel-air:8080, http://travel-ground:8080, http://travel-sea:8080"
  MESSAGE: "Travel aggregator working very hard to understand where the hell you want to go :D"
  NAME: "travel-avail"
  SERVER_TYPE: "http"
  TIMING_50_PERCENTILE: 30ms
  TIMING_90_PERCENTILE: 60ms
  TIMING_99_PERCENTILE: 90ms
  TRACING_ZIPKIN: "http://tracing-jaeger:9411"
