---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ground-train
  namespace: {{ .Values.namespace }}
data:
  LISTEN_ADDR: 0.0.0.0:8080
  MESSAGE: "It's easier for all of us if you buy a rail pass :P"
  NAME: "ground-train"
  SERVER_TYPE: "http"
  TIMING_50_PERCENTILE: 30ms
  TIMING_90_PERCENTILE: 60ms
  TIMING_99_PERCENTILE: 90ms
  TRACING_ZIPKIN: "http://tracing-jaeger:9411"
