---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-avail
  namespace: {{ .Values.namespace }}
data:
  LISTEN_ADDR: 0.0.0.0:8080
  UPSTREAM_URIS: "http://hotel-internal:8080, http://hotel-external:8080"
  MESSAGE: "Hotel availability is working hard to aggregate internal and external results. So exhausting!"
  NAME: "hotel-avail"
  SERVER_TYPE: "http"
  TIMING_50_PERCENTILE: 30ms
  TIMING_90_PERCENTILE: 60ms
  TIMING_99_PERCENTILE: 90ms
  TRACING_ZIPKIN: "http://tracing-jaeger:9411"
