---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prey-acid-slime
  namespace: {{ .Values.namespace }}
data:
  LISTEN_ADDR: 0.0.0.0:8080
  MESSAGE: "HELP! I'm an lonely prey for wild Acid slimes!"
  NAME: "prey-acid-slime"
  SERVER_TYPE: "http"
  TIMING_50_PERCENTILE: 30ms
  TIMING_90_PERCENTILE: 60ms
  TIMING_99_PERCENTILE: 90ms
  TRACING_ZIPKIN: "http://tracing-jaeger:9411"
