apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prey-acid-slime.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "prey-acid-slime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prey-acid-slime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "prey-acid-slime.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prey-acid-slime.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
#            httpGet:
#              path: /
#              port: http
          readinessProbe:
            tcpSocket:
              port: 8080
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ERROR_RATE
              value: "0"
            - name: ERROR_TYPE
              value: "http_error"
            - name: ERROR_CODE
              value: "500"
          envFrom:
            - configMapRef:
                name: prey-acid-slime
